export const dummyData = {
    testPackageName: "Simulasi Tryout Bahasa Korea",
    remainingDuration: 600, // 10 menit
    questions: [
        {
            id: "q1",
            questionText: "",
            questionVoice: "",
            questionImage: "https://res.cloudinary.com/dtxx1gcip/image/upload/v1752126857/opl7yrrpyrbrmzflhrdx.png",
            options: [
                { id: "a", optionText: "칼" },
                { id: "b", optionText: "가위" },
                { id: "c", optionText: "젓가락" },
                { id: "d", optionText: "숟가락" },
            ],
            correctOptionId: "b",
        },
        {
            id: "q2",
            questionText: "",
            questionVoice: "",
            questionImage: "https://res.cloudinary.com/dtxx1gcip/image/upload/v1752126883/e0dlhp1g0pqgioe0f63q.png",
            options: [
                { id: "a", optionText: " 공입니다." },
                { id: "b", optionText: " 가위입니다." },
                { id: "c", optionText: "거울입니다." },
                { id: "d", optionText: "안경입니다" },
            ],
            correctOptionId: "c",
        },
        {
            id: "q3",
            questionText: "",
            questionVoice: "",
            questionImage: "https://res.cloudinary.com/dtxx1gcip/image/upload/v1752126906/xn0d76mqembh1txugh30.png",
            options: [
                { id: "a", optionText: "구두가 세 켤레 있습니다." },
                { id: "b", optionText: "구두가 네 켤레 있습니다." },
                { id: "c", optionText: "구두가 다섯 켤레 있습니다." },
                { id: "d", optionText: "구두가 여섯 켤레 있습니다." },
            ],
            correctOptionId: "b",
        },
        {
            id: "q4",
            questionText: " 다음 단어와 관계있는 것은 무엇입니까?  곱하기. 나누기. 더하기. 빼기. ",
            questionVoice: "",
            questionImage: "",
            options: [
                { id: "a", optionText: "역사" },
                { id: "b", optionText: "생물학" },
                { id: "c", optionText: "수학" },
                { id: "d", optionText: "언어학" },
            ],
            correctOptionId: "c",
        },
        {
            id: "q5",
            questionText: "다음 단어의 비슷한말은 무엇입니까? 조금",
            questionVoice: "",
            questionImage: "",
            options: [
                { id: "a", optionText: "약간" },
                { id: "b", optionText: "점점" },
                { id: "c", optionText: "지금" },
                { id: "d", optionText: "종종" },
            ],
            correctOptionId: "a",
        },
        {
            id: "q6",
            questionText: "",
            questionVoice: "https://res.cloudinary.com/dtxx1gcip/video/upload/v1752126749/el97i7acr5cmmevbf76m.mp3",
            questionImage: "",
            options: [
                { id: "a", optionText: "아이" },
                { id: "b", optionText: "오이" },
                { id: "c", optionText: "우유" },
                { id: "d", optionText: "아우" },
            ],
            correctOptionId: "c",
        },
        {
            id: "q7",
            questionText: "",
            questionVoice: "https://res.cloudinary.com/dtxx1gcip/video/upload/v1752126748/mxz78ehpxhva802vplln.mp3",
            questionImage: "",
            options: [
                { id: "a", optionText: "공책" },
                { id: "b", optionText: "책상" },
                { id: "c", optionText: "경찰" },
                { id: "d", optionText: "명찰" },
            ],
            correctOptionId: "d",
        },
        {
            id: "q8",
            questionText: "",
            questionVoice: "https://res.cloudinary.com/dtxx1gcip/video/upload/v1752126748/ghs996ysalw3zrtbyj5t.mp3",
            questionImage: "",
            options: [
                { id: "a", optionText: "같이 갔어요." },
                { id: "b", optionText: "꽃이 없어요." },
                { id: "c", optionText: " 가치가 없어요." },
                { id: "d", optionText: " 기차가 왔어요." },
            ],
            correctOptionId: "b",
        },
        {
            id: "q9",
            questionText: "",
            questionVoice: "https://res.cloudinary.com/dtxx1gcip/video/upload/v1752126748/e3chwrsctczsvljovs2u.mp3",
            questionImage: "",
            options: [
                { id: "a", optionText: "저는 5 살에 학교에 입학했어요." },
                { id: "b", optionText: " 저는 6 살에 학교에 입학했어요." },
                { id: "c", optionText: " 저는 7 살에 학교에 입학했어요." },
                { id: "d", optionText: " 저는 8 살에 학교에 입학했어요." },
            ],
            correctOptionId: "b",
        },
        {
            id: "q10",
            questionText: "이것은 무엇입니까?",
            questionVoice: "https://res.cloudinary.com/dtxx1gcip/video/upload/v1752126749/ratrqicwounzmg0n9dp2.mp3",
            questionImage: "https://res.cloudinary.com/dtxx1gcip/image/upload/v1752127723/wthag0nuyjjti7jvusum.png",
            options: [
                { id: "a", optionText: "1" },
                { id: "b", optionText: "2" },
                { id: "c", optionText: "3" },
                { id: "d", optionText: "4" },
            ],
            correctOptionId: "c",
        },
    ],
};